### ISSUE TITLE
Plan for Importing and Testing Code Snippets

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#335] opened 2020-10-01 23:55 UTC
We currently have an example of how to import and test code snippets: the Zoe Intro ([markdown](https://github.com/Agoric/documentation/blob/master/main/getting-started/intro-zoe.md), [code snippets](https://github.com/Agoric/documentation/blob/master/snippets/test-intro-zoe.js).)

However, there is a lot of code in this repository that is not tested. This issue can serve as an overall plan for tackling this, and we can create smaller issues for particular subtasks.

First, let's not tackle the `/api/` docs since those may be automated from agoric-sdk in the near future. So that leaves:

- [ ] distributed-programming.md
- [ ] wallet-api.md
- [ ] alpha-release-candidate.md
- [ ] dapps/README.md
- [ ] ertp/guide/ (all of it) #336 
- [ ] getting-started/ (all of it)
- [ ] zoe/guide/
- [ ] zoe/guide/contracts/ #337 

I think we should start with the ERTP Guide and Zoe Guide Contracts. I'll create separate issues for those two.

**Comment by Tyrosine22** [comment] 2023-01-10 18:53
Duplicate of #751

**Closed** 2023-01-10 18:53 UTC
Labels: Snippets, wontfix, documentation
