### ISSUE TITLE
SyntaxError: The requested module '@agoric/nat' does not provide an export named 'Nat'

### ISSUE THREAD

**Issue by HadrienPierart** [Agoric/documentation#601] opened 2021-12-25 15:59 UTC
When trying to run "agoric" command from a command line which is not pointing to a minimal node v14 as mentionned in the documentation, this cryptic error is thrown.

This is especially relevant if you manage multiple node version with nvm and node 14 is not your default version.

Solution : `nvm use 14` (or install node 14) and this error disappears

**Comment by dckc** [comment] 2021-12-25 17:04
I agree the error message is cryptic.

Exactly what steps does it take to reproduce it? I get a different message:

```
$ agoric
/.../agoric-sdk/packages/agoric-cli/src/entrypoint.js:5
import '@agoric/install-ses/pre-bundle-source.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

This problem is also noted in https://github.com/Agoric/agoric-sdk/issues/3857#issue-1001522029 ; I was going to mark this one as a dup, but the scope of that one is more broad.

**Comment by tgrecojs** [comment] 2022-01-07 17:07
running `agoric` on it's own doesn't get me into this situation, but i have seen it a handful of times (just ran into it moments ago while walking through the process of configuring eslint with the jessie plug-in noted in the docs)

again, i'm not running into this error running the cli, however i'm pretty sure that it usually boils down to a package.json missing the following property: `type: "module"`. looking at the stack trace of the error @dckc is getting leads me to believe that `packages/agoric-cli` might be missing this property assignment 🤔

**Comment by Tyrosine22** [comment] 2023-01-10 04:54
This error message is out of scope since it isn't really an Agoric error message. If it was easily reproduced, I'd go ahead & document it anyways, but as it is, it doesn't seem worth the bother of documenting.

**Comment by dckc** [comment] 2023-01-10 07:59
Not an Agoric error message? I wonder what you mean by that or how folks are supposed to know. What they know is that they tried out tool and it spit out a diagnostic that doesn't help them diagnose the problem, which is that the version of node they're using is out of date.

Maybe it's not a doc bug but a but in agoric-sdk.

**Comment by dckc** [comment] 2023-12-22 04:37
most likely overtaken by events

**Closed by dckc** 2023-12-22 04:37 UTC
Labels: documentation
